CREATE TABLE QUESTION(ID INT PRIMARY KEY AUTO_INCREMENT , SUBJECT VARCHAR(2000), TOPICS VARCHAR(1000), DIFFICULTY INT);


INSERT INTO QUESTION(SUBJECT, TOPICS, DIFFICULTY) VALUES('What is Java?', 'Programming', 3);
				
select * from question;